/* Write your PL/SQL query statement below */
SELECT CONTEST_ID,
        ROUND(COUNT(DISTINCT USER_ID) * 100 / (SELECT COUNT(USER_ID) FROM Users), 2) PERCENTAGE
FROM Register
GROUP BY CONTEST_ID
ORDER BY PERCENTAGE DESC, CONTEST_ID;