-- 각 기계의 프로세스별 작동 시간을 구하고, 평균을 구해 3자리수까지 나타내기
SELECT A.MACHINE_ID, ROUND(AVG(B.TIMESTAMP - A.TIMESTAMP), 3) PROCESSING_TIME
FROM Activity A, ACTIVITY B
WHERE A.MACHINE_ID = B.MACHINE_ID 
AND A.PROCESS_ID = B.PROCESS_ID
AND A.ACTIVITY_TYPE = 'start'
AND B.ACTIVITY_TYPE = 'end'
GROUP BY A.MACHINE_ID;