-- CROSS JOIN ! 조건없이 모두 매칭
SELECT S.STUDENT_ID, S.STUDENT_NAME, SUB.SUBJECT_NAME, COUNT(E.SUBJECT_NAME) ATTENDED_EXAMS
FROM Students S CROSS JOIN Subjects Sub LEFT JOIN Examinations E
ON S.Student_id = E.Student_id AND Sub.subject_name = E.subject_name
GROUP BY S.STUDENT_ID, S.STUDENT_NAME, SUB.SUBJECT_NAME
ORDER BY STUDENT_ID, STUDENT_NAME;